coderslab/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from exercises.views import SchoolView, SchoolClassView, StudentView, GradesView, StudentSearchFormView, \
    StudentAddFormView, PizzaToppingsView, UserValidationView, UsersView, LoginView, LogoutView, ResetPassword

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', SchoolView.as_view(), name="index"),
    url(r'^class/(?P<school_class>(\d)+)', SchoolClassView.as_view(), 
        name="school-class"),
    url(r'^students/(?P<student_id>(\d)+)', StudentView.as_view(), name="students"),
    url(r'^grades/(?P<student_id>(\d)+)/(?P<subject_id>(\d)+)', GradesView.as_view(), name="grades"),
    url(r'^student_search/', StudentSearchFormView.as_view(), name="search_student"),
    url(r'^student_add/', StudentAddFormView.as_view(), name="add_student"),
    url(r'^pizza/', PizzaToppingsView.as_view(), name="pizza"),
    url(r'^d2_p3_e1/', UserValidationView.as_view(), name="user_validation"),
    url(r'^list_users/', UsersView.as_view(), name='users_view'),
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^logout', LogoutView.as_view(), name='logout'),
    url(r'^reset_password/(?P<user_id>(\d)+)', ResetPassword.as_view(), name='reset_password'),
]

exercises/models.py
from django.db import models


SCHOOL_CLASS = (
    (1, "1a"),
    (2, "1b"),
    (3, "2a"),
    (4, "2b"),
    (5, "3a"),
    (6, "3b"),
)


GRADES = (
    (1, "1"),
    (1.5, "1+"),
    (1.75, "2-"),
    (2, "2"),
    (2.5, "2+"),
    (2.75, "3-"),
    (3, "3"),
    (3.5, "3+"),
    (3.75, "4-"),
    (4, "4"),
    (4.5, "4+"),
    (4.75, "5-"),
    (5, "5"),
    (5.5, "5+"),
    (5.75, "6-"),
    (6, "6")
)


# Create your models here.
class SchoolSubject(models.Model):
    name = models.CharField(max_length=64)
    teacher_name = models.CharField(max_length=64)


class Student(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    school_class = models.IntegerField(choices=SCHOOL_CLASS)
    grades = models.ManyToManyField(SchoolSubject, through="StudentGrades")
    year_of_birth = models.IntegerField(blank=True, null=True)

    @property
    def name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        return self.name


class StudentGrades(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    school_subject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE)
    grade = models.FloatField(choices=GRADES)

exercises/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import CheckboxSelectMultiple, RadioSelect, ModelForm

from exercises.models import SCHOOL_CLASS


class SearchStudentForm(forms.Form):
    last_name = forms.CharField(label="Wyszukaj po nazwisku", max_length=64)


class AddStudentForm(forms.Form):
    name = forms.CharField(label="Imię", max_length=30)
    surname = forms.CharField(label="Nazwisko", max_length=40)
    klasa = forms.ChoiceField(choices=SCHOOL_CLASS)


TOPPINGS=(
    (1, "Oliwki"),
    (2, "Pomidory"),
    (3, "Dodatkowy ser"),
    (4, "Cebula"),
    (5, "Anszua"),
    (6, "Wincyj Cebuli"),
    )


class PizzaToppingsForm(forms.Form):
    toppings = forms.MultipleChoiceField(choices=TOPPINGS, widget=CheckboxSelectMultiple)


class UserValidationForm(forms.Form):
    first_name = forms.CharField(label="Imie", max_length=64)
    last_name = forms.CharField(label="Nazwisko", max_length=64)
    email = forms.EmailField(label="Email", max_length=64)
    url = forms.URLField(label="WWW", max_length=100)


class UserForm(forms.Form):
    username = forms.CharField(max_length=64)
    password = forms.CharField(widget=forms.PasswordInput)


class ResetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    repeat_password = forms.CharField(widget=forms.PasswordInput)

exercises/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages

from exercises.forms import SearchStudentForm, AddStudentForm, PizzaToppingsForm, UserValidationForm, UserForm, \
    ResetPasswordForm
from .models import SCHOOL_CLASS, Student, SchoolSubject, StudentGrades


# Create your views here.
class SchoolView(View):

    def get(self, request):
        return render(request, "school.html",
                      {"SCHOOL_CLASS": SCHOOL_CLASS})


class SchoolClassView(View):
    def get(self, request, school_class):
        students = Student.objects.filter(school_class=school_class)
        return render(request, "class.html", {"students": students,
                                              "class_name": SCHOOL_CLASS[int(school_class) - 1][1]})


class StudentView(View):
    def get(self, request, student_id):
        student = Student.objects.get(pk=student_id)
        subjects = SchoolSubject.objects.all()
        return render(request, "students.html", {"student": student,
                                                 "subjects": subjects})


class GradesView(View):
    def get(self, request, student_id, subject_id):
        student = Student.objects.get(pk=student_id)
        grades = StudentGrades.objects.filter(school_subject=subject_id, student=student_id)
        average = []
        for g in grades:
            average.append(g.grade)

        if len(average) > 0:
            av = sum(average) / len(average)
        else:
            av = 0
        return render(request, "grades.html", {"student": student,
                                               "grades": grades,
                                               "average": av})


class StudentSearchFormView(View):
    def get(self, request):
        form = SearchStudentForm()
        if "last_name" in request.GET:
            search_ctx = request.GET["last_name"]
            students = Student.objects.filter(last_name__icontains=search_ctx)
        else:
            students = None
        return render(request, "student_search_form.html", {"form": form,
                                                            "students": students})


class StudentAddFormView(View):
    def get(self, request):
        form = AddStudentForm()
        return render(request, "student_add.html", {"form": form})

    def post(self, request):
        form = AddStudentForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            klasa = form.cleaned_data['klasa']
            Student.objects.create(first_name=name, last_name=surname, school_class=klasa)
            return HttpResponseRedirect('/student_add/')


class PizzaToppingsView(View):
    def get(self, request):
        form = PizzaToppingsForm()
        return render(request, "pizza_toppings.html", {"form": form})


class UserValidationView(View):
    def get(self, request):
        form = UserValidationForm()
        return render(request, "user_validation.html", {"form": form})

    def post(self, request):
        form = UserValidationForm(request.POST)
        if form.is_valid():
            return render(request, "user_validation.html", {"form": form})
        else:
            return render(request, "user_validation.html", {"form": form})


class UsersView(View):
    def get(self, request):
        users = User.objects.all()
        return render(request, "users.html", {"users": users})


class LoginView(View):
    def get(self, request):
        form = UserForm()
        return render(request, 'login.html', {"form": form})

    def post(self, request):
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('users_view')
        return redirect('login')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('users_view')


class ResetPassword(PermissionRequiredMixin, View):
    permission_required = 'auth.change_user'
    def get(self, request, user_id):
        form = ResetPasswordForm()
        return render(request, 'reset_password.html', {"form": form,
                                                       "user_id": user_id})

    def post(self, request, user_id):
        form = ResetPasswordForm(request.POST)
        if form.is_valid(): # and request.user.has_perm("auth.change_user"):
            password = form.cleaned_data['password']
            repeat_password = form.cleaned_data['repeat_password']
            if password == repeat_password:
                user = User.objects.get(pk=user_id)
                user.set_password(password)
                user.save()
                messages.success(request, 'Your password was successfully changed')
            else:
                print("Warning is added")
                messages.warning(request, 'Something went horribly wrong!')
        else:
            messages.warning(request, 'You dont have permissions to do that')
        return redirect('reset_password', user_id=user_id)

exercises/templates/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
    <div class="container">
    {% load static %}

    <img src="{% static 'logo.png' %}" alt="Logo" class="img-fluid rounded mx-auto d-block">
        {%  block content %}
        {%  endblock %}
    </div>

     {% if user.is_authenticated %}
         <p>Zalogowany użytkownik: {{ user.username }}</p>
         <a href="/logout">Wyloguj</a>
    {% else %}
         <p>Żodyn nie zalogowany</p>
         <a href="/login">Zaloguj</a>
    {% endif %}

    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}


    </body>
</html>

exercises/templates/class.html
{% extends "base.html" %}

{% block content %}


<a href="{% url 'index' %} "><- Wróc do listy klas</a>

<h2>Uczniowie klasy {{ class_name }}:</h2>

    <table class="table">
        <tr>
            <th>Link</th>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>Klasa</th>
        </tr>
        {% for s in students %}
        <tr>
            <td><a href="{% url 'students' s.id %}">{{  s.id }}</a></td>
            <td>{{ s.first_name }}</td>
            <td>{{ s.last_name }}</td>
            <td>{{ s.school_class }}</td>
        </tr>
        {% endfor %}
    </table>
{%  endblock %}

exercises/templates/grades.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'students' student.id %}"><- Powrót do listy przedmiotów ucznia</a>

<h2>Oceny ucznia {{ student.name }}:</h2>

    <table class="table">
        <tr>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>Klasa</th>
        </tr>
        <tr>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.get_school_class_display }}</td>
        </tr>

    </table>
    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th>Ocena</th>
            <th>Przedmiot</th>
            <th>Prowadzący</th>
        </tr>
        </thead>
        <tbody>
            {% for g in grades %}
            <tr>
                <td>{{ g.get_grade_display }}</td>
                <td>{{ g.school_subject.name }}</td>
                <td>{{ g.school_subject.teacher_name }}</td>
            </tr>
            {% endfor %}

            {% if average > 0 %}
            <tr>
                <td>Średnia: {{ average }}</td>
            </tr>
            {% else %}
            <tr>
                <td>Uczeń nie ma jeszcze ocen</td>
            </tr>
            {% endif %}
       </tbody>
{%  endblock %}

exercises/templates/login.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'login' %}" method="post">
    <div class="form-row align-items-center">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <input type="submit" value="ok" class="btn btn-primary">
</form>
{% endblock %}

exercises/templates/pizza_toppings.html
{%  extends 'base.html' %}

{% block content %}
<form action="{% url 'pizza' %}" method="get">
    {{ form.as_p }}
    <input type="submit" value="Dej mnie">
</form>
{% endblock %}

exercises/templates/reset_password.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'reset_password' user_id=user_id %}" method="post">
    <div class="form-row align-items-center">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <input type="submit" value="ok" class="btn btn-primary">
</form>
{% endblock %}

exercises/templates/school.html
{% extends "base.html" %}

{% block content %}
<h1>Szkoła podstawowa nr 1 im. Chucka Norrisa.</h1>
<h2>Klasy:</h2>
<ul>
{% for class in SCHOOL_CLASS %}
    <li><a href='{%  url 'school-class' class.0 %}'>{{ class.1 }}</a></li>
{% endfor %}
</ul>
{%  endblock %}

exercises/templates/student_add.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'add_student' %}" method="post">
    <div class="form-row align-items-center">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <input type="submit" value="ok" class="btn btn-primary">
</form>
{% endblock %}

exercises/templates/student_search_form.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'search_student' %}" method="get">
    {{ form }}
    <input type="submit" value="ok">
</form>

    {% if students %}
        <table class="table">
            {% for s in students %}
                <tr>
                <td>{{ s.name }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

exercises/templates/students.html
{% extends "base.html" %}

{% block content %}

    <a href="{%  url 'school-class' student.school_class %}"><- Powrót do listy uczniów</a>

<h2>Uczeń {{ student.name }}:</h2>


    <table class="table">
        <tr>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>Klasa</th>
        </tr>
        <tr>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.get_school_class_display }}</td>
        </tr>
    </table>

    <table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Przedmiot</th>
            <th>Prowadzący</th>
        </tr>
    </thead>
    <tbody>
            {% for s in subjects %}
            <tr>
                <td><a href="/grades/{{ student.id }}/{{ s.id }}">{{ s.name }}</a></td>
                <td>{{ s.teacher_name }}</td>
            </tr>
            {% endfor %}
    </tbody>
    </table>

{%  endblock %}

exercises/templates/user_validation.html
{%  extends 'base.html' %}

{% block content %}
<form action="{% url 'user_validation' %}" method="post">
{%  csrf_token %}
    {{ form }}
    <input type="submit" value="Waliduj">
</form>

    {% if form.email.value is not None %}
        Dane poprawne dla:
            <table>
                {% for field in form %}
                <tr>
                    <td>{{ field.value }}</td>
                </tr>
                {% endfor %}
            </table>

    {% endif %}

{% endblock %}

exercises/templates/users.html
{% extends "base.html" %}

{% block content %}
<h1>Lista użytkowników:</h1>

<ul>
{% for u in users %}
    <li>Login: {{ u.username }}, Nazwisko: {{ u.last_name }}</li>
{% endfor %}
</ul>
{%  endblock %}